Repository falgon/roki-web, pull requests merged in 2022-12, with the labels that each got.

#353 update icons and hobbies
  contents/templates/site/author-info/more-links.html
  src/Contexts/Core.hs
Labels: automerge

#355 master <- develop
  .github/workflows/codeql.yml
  .github/workflows/kiirotori-auto-approve.yml
  contents/templates/site/author-info/more-links.html
  src/Contexts/Core.hs
Labels: dependencies, automerge

#358 master <- develop
  contents/templates/blog/post-list.html
  src/Rules/Blog/Core.hs
Labels: dependencies, automerge

#359 resize profile images to 740px
  contents/images/avator/prof1000x1000.png
  contents/images/avator/prof1000x1000.png.webp
Labels: refactoring, automerge

#365 master <- develop
  contents/images/avator/prof1000x1000.png
  contents/images/avator/prof1000x1000.png.webp
  package-lock.json
  package.json
Labels: dependencies, automerge

#366 develop <- master
  contents/roki.diary/2016/12/18/beer-is-good/index.md
  contents/roki.diary/2017/04/16/rokuro/index.md
  contents/roki.diary/2022/09/20/gs-sbga439-review/index.md
  contents/roki.diary/2022/12/11/fascinated-by-watches/index.md
  contents/roki.diary/2022/12/11/fascinated-by-watches/iwc_portuguese.jpg
Labels: dependencies, automerge

#367 develop <- master
  contents/roki.diary/2022/12/11/fascinated-by-watches/index.md
Labels: dependencies, automerge

#369 develop <- master
  contents/roki.diary/2022/12/11/fascinated-by-watches/iwc_portuguese.jpg
Labels: dependencies, automerge

#370 Fix author links
  contents/scss/base/_all.scss
  contents/scss/base/_colors.scss
  contents/scss/base/_default.scss
  contents/templates/blog/share-icons.html
  contents/templates/site/author-info/listed.html
  contents/templates/site/author-info/more-links.html
  contents/templates/site/author-info/pc.html
  contents/templates/site/author-info/sp.html
  src/Contexts/Core.hs
Labels: automerge, style

#371 master <- develop
  contents/scss/base/_all.scss
  contents/scss/base/_colors.scss
  contents/scss/base/_default.scss
  contents/templates/blog/share-icons.html
  contents/templates/site/author-info/listed.html
  contents/templates/site/author-info/more-links.html
  contents/templates/site/author-info/pc.html
  contents/templates/site/author-info/sp.html
  src/Contexts/Core.hs
Labels: dependencies, automerge

#373 fix top page style
  contents/templates/site/author-info/listed.html
  contents/templates/site/author-info/more-links.html
  contents/templates/site/author-info/pc.html
  contents/templates/site/author-info/sp.html
  contents/templates/site/blogs-intro/diary-post-list.html
  contents/templates/site/blogs-intro/tech-post-list.html
Labels: automerge, style

#374 master <- develop
  contents/templates/site/author-info/listed.html
  contents/templates/site/author-info/more-links.html
  contents/templates/site/author-info/pc.html
  contents/templates/site/author-info/sp.html
  contents/templates/site/blogs-intro/diary-post-list.html
  contents/templates/site/blogs-intro/tech-post-list.html
  package-lock.json
  package.json
Labels: dependencies, automerge

#375 add updated badge
  contents/scss/base/_default.scss
  contents/templates/site/blogs-intro.html
  src/Rules/IndexPage.hs
Labels: automerge, style

#377 master <- develop
  contents/scss/base/_default.scss
  contents/templates/site/blogs-intro.html
  src/Rules/IndexPage.hs
Labels: dependencies, automerge
