Repository falgon/roki-web, pull requests merged in 2023-02, with the labels that each got.

#394 Fix Circle CI badge URL
  .circleci/config.yml
Labels: bug, CI, automerge

#396 CI add manually build
  .circleci/config.yml
  .github/workflows/build_pr.yml
Labels: CI, automerge

#399 CI fix passing circle ci branch name
  .circleci/config.yml
  .github/workflows/build_pr.yml
Labels: CI, automerge

#398 Fix CI deprecated
  .github/workflows/manually-gh-registry.yml
Labels: CI, automerge

#402 Fix commit id link from tori message
  .circleci/config.yml
Labels: CI, automerge

#404 master <- develop
  .circleci/config.yml
  .github/workflows/build.yml
  .github/workflows/build_pr.yml
  .github/workflows/cleanup-cache.yml
  .github/workflows/manually-cleanup-caches.yml
  .github/workflows/manually-gh-registry.yml
  package-lock.json
  package.json
Labels: dependencies, automerge

#397 Use manually psi from build workflow
  .github/workflows/build.yml
  .github/workflows/psi.yml
Labels: CI, automerge

#405 master <- develop
  .github/workflows/build.yml
  .github/workflows/psi.yml
  package-lock.json
  package.json
Labels: dependencies, automerge

#406 develop <- master
  contents/roki.diary/2022/12/11/fascinated-by-watches/index.md
  contents/roki.log/2021/07/10/SelfMadeTinyGit/index.md
Labels: dependencies, automerge

#407 master <- develop
  contents/templates/site/donate.html
Labels: dependencies, automerge

#413 Add artifacts cleanup CI
  .github/workflows/cleanup-artifacts.yml
Labels: CI, automerge

#414 Remove artifacts generated by a specific workflow after it runs
  .github/workflows/build.yml
  .github/workflows/build_pr.yml
  .github/workflows/cleanup-artifacts.yml
  .github/workflows/manually-cleanup-artifacts.yml
Labels: CI, automerge

#415 master <- develop
  .github/workflows/build.yml
  .github/workflows/build_pr.yml
  .github/workflows/cleanup-artifacts.yml
  .github/workflows/manually-cleanup-artifacts.yml
Labels: dependencies, automerge

#416 develop <- master
  contents/roki.diary/2022/09/20/gs-sbga439-review/index.md
  contents/roki.diary/2023/02/18/camel-resort-glamping/anker_sound.jpg
  contents/roki.diary/2023/02/18/camel-resort-glamping/bbq.jpg
  contents/roki.diary/2023/02/18/camel-resort-glamping/bbq_set.jpg
  contents/roki.diary/2023/02/18/camel-resort-glamping/buggy.jpg
  contents/roki.diary/2023/02/18/camel-resort-glamping/camel_with_me.jpg
  contents/roki.diary/2023/02/18/camel-resort-glamping/day2_lunch.jpg
  contents/roki.diary/2023/02/18/camel-resort-glamping/dome.jpg
  contents/roki.diary/2023/02/18/camel-resort-glamping/foot_golf_image.jpg
  contents/roki.diary/2023/02/18/camel-resort-glamping/glamping-dome.jpg
  contents/roki.diary/2023/02/18/camel-resort-glamping/hamburger.jpg
  contents/roki.diary/2023/02/18/camel-resort-glamping/hammock_with_me.jpg
  contents/roki.diary/2023/02/18/camel-resort-glamping/index.md
  contents/roki.diary/2023/02/18/camel-resort-glamping/lightup_with_me.jpg
  contents/roki.diary/2023/02/18/camel-resort-glamping/morning.jpg
  contents/roki.diary/2023/02/18/camel-resort-glamping/my_coffee.png
  contents/roki.diary/2023/02/18/camel-resort-glamping/sunset.jpg
  contents/roki.diary/2023/02/18/camel-resort-glamping/wakashio_with_me.jpg
Labels: dependencies, automerge

#418 restyle readmore buttons
  contents/templates/blog/post-list.html
Labels: automerge, style

#419 master <- develop
  contents/templates/blog/post-list.html
Labels: dependencies, automerge

#420 develop <- master
  contents/roki.diary/2022/09/20/gs-sbga439-review/index.md
  contents/roki.diary/2022/09/20/gs-sbga439-review/lug_point.jpg
Labels: dependencies, automerge
