Repository falgon/roki-web, pull requests merged in 2023-11, with the labels that each got.

#469 master <- develop
  .circleci/config.yml
  .github/workflows/build_pr.yml
  package-lock.json
  package.json
Labels: dependencies, automerge

#471 Add clean when it detects an EAGAIN
  .github/workflows/build_pr.yml
Labels: CI, automerge

#473 master <- develop
  .github/workflows/build_pr.yml
Labels: dependencies, automerge

#474 develop <- master
  contents/roki.log/2023/11/09/add-new-web-api-send-plain-text/message_from_bot.jpg
  contents/roki.log/2023/11/09/add-new-web-api-send-plain-text/overview.png
Labels: dependencies, automerge

#475 Without message `connecting`
  app/spa/Main.hs
Labels: automerge
