Repository falgon/roki-web, pull requests merged in 2025-01, with the labels that each got.

#636 develop <- master
  contents/resume/career/6.md
Labels: documentation, dependencies, automerge

#637 update new images
  contents/images/avator/favicon.ico
  contents/images/avator/prof1000x1000.png
  contents/images/avator/prof1000x1000.png.webp
Labels: automerge

#639 master <- develop
  contents/images/avator/favicon.ico
  contents/images/avator/prof1000x1000.png
  contents/images/avator/prof1000x1000.png.webp
  package-lock.json
  package.json
Labels: dependencies, automerge

#640 update cache version to v4 and using ubuntu24.04
  .github/workflows/build.yml
  .github/workflows/build_pr.yml
  .github/workflows/haddock.yml
  .github/workflows/manually-gh-registry.yml
  .github/workflows/psi.yml
Labels: CI, automerge

#642 update go version to 1.23.4
  .circleci/config.yml
  .github/workflows/build_pr.yml
Labels: CI, automerge
