Repository falgon/roki-web, pull requests merged in 2025-09, with the labels that each got.

#746 master <- develop
  .circleci/config.yml
  .github/workflows/build_pr.yml
  package-lock.json
  package.json
Labels: CI, dependencies, automerge

#744 feat(disney): ディズニー体験ページに宿泊概算セクションを追加
  contents/config/disney/Hotels.dhall
  contents/pages/disney_experience_summary/jp.html
  contents/scss/disney_experience_summary_only.scss
  hoge.txt
  src/Rules/DisneyExperienceSummary.hs
Labels: automerge, style, pages

#749 feat: Disney体験ログにAI生成フラグ機能を追加
  .gitignore
  contents/pages/disney_experience_summary/jp.html
  contents/scss/disney_experience_summary_only.scss
  src/Rules/DisneyExperienceSummary.hs
Labels: automerge, feature

#753 Update pr-labeler.yml
  .github/pr-labeler.yml
Labels: CI, automerge

#765 master <- develop
  .github/pr-labeler.yml
  .github/workflows/claude-code-review.yml
  .github/workflows/claude.yml
  CLAUDE.md
  contents/config/disney/Hotels.dhall
  hoge.txt
  package-lock.json
  package.json
  src/Rules/DisneyExperienceSummary.hs
Labels: documentation, CI, dependencies, automerge

#726 refactor: consolidate multiple Dockerfiles into single multi-stage build (#589)
  .github/workflows/manually-gh-registry.yml
  Makefile
  docker/Dockerfile
  docker/README.md
  docker/contents/Dockerfile
  docker/dev/Dockerfile
  docker/docker-compose-ghcr.yml
  docker/docker-compose.yml
  tools/github-actions/NotifyBuildCompletion.hs
Labels: automerge, docker

#769 develop <- master
  contents/disney_experience_summary/logs/100.md
  contents/disney_experience_summary/logs/62.md
Labels: documentation, dependencies, automerge

#770 master <- develop
  .github/workflows/manually-gh-registry.yml
  Makefile
  docker/Dockerfile
  docker/README.md
  docker/contents/Dockerfile
  docker/dev/Dockerfile
  docker/docker-compose-ghcr.yml
  docker/docker-compose.yml
  package-lock.json
  package.json
  tools/github-actions/NotifyBuildCompletion.hs
Labels: documentation, CI, dependencies, automerge, docker
