Repository falgon/roki-web, pull requests merged in 2025-07, with the labels that each got.

#703 refactoring: replace all js to ts
  contents/js/components.js
  contents/js/uniq_tab.js
  contents/ts/components.ts
  contents/ts/uniq_tab.ts
  package-lock.json
  package.json
  src/Vendor/FontAwesome/Core.hs
  tools/fontawesome.js
  tools/fontawesome.ts
  tools/katex.ts
  tools/katex_runner.sh
  tools/ts-stdin-compile.sh
  tools/ts-stdin-compile.ts
Labels: refactoring, automerge, javascript

#708 master <- develop
  .github/workflows/codeql.yml
  .github/workflows/pr-labeler.yml
  contents/js/components.js
  contents/js/uniq_tab.js
  contents/ts/components.ts
  contents/ts/uniq_tab.ts
  package-lock.json
  package.json
  src/Vendor/FontAwesome/Core.hs
  tools/fontawesome.js
  tools/fontawesome.ts
  tools/katex.ts
  tools/katex_runner.sh
  tools/ts-stdin-compile.sh
  tools/ts-stdin-compile.ts
Labels: CI, dependencies, automerge

#712 Update Ubuntu image version using gh registry workflow
  .github/workflows/manually-gh-registry.yml
Labels: CI, automerge

#710 develop <- master
  contents/resume/career/6.md
  contents/resume/career/7.md
Labels: documentation, dependencies, automerge
