Repository falgon/roki-web, pull requests merged in 2025-08, with the labels that each got.

#720 Add disney page redirects
  src/Rules/DisneyExperienceSummary.hs
Labels: automerge

#717 [Snyk] Security upgrade ubuntu from 24.04 to 24.10
  docker/contents/Dockerfile
Labels: automerge, docker

#722 ci: Qltyコード品質ツールの設定ファイルを追加
  .qlty/qlty.toml
Labels: CI, automerge

#725 feat: Disney Experience Summaryのタグをアルファベット順にソート
  src/Rules/DisneyExperienceSummary.hs
Labels: refactoring, automerge

#724 master <- develop
  .qlty/qlty.toml
  docker/contents/Dockerfile
  docker/dev/Dockerfile
  src/Rules/DisneyExperienceSummary.hs
Labels: dependencies, automerge, docker

#730 develop <- master
  contents/disney_experience_summary/logs/33.md
  contents/disney_experience_summary/logs/34.md
  contents/disney_experience_summary/logs/47.md
  contents/disney_experience_summary/logs/49.md
  contents/disney_experience_summary/logs/50.md
  contents/disney_experience_summary/logs/51.md
  contents/disney_experience_summary/logs/52.md
  contents/disney_experience_summary/logs/53.md
  contents/resume/career/7.md
Labels: documentation, dependencies, automerge
